<?xml version="1.0" ?>
<robot name='two_wheeled_stick_robot' xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="stick_length" value="0.5"/>
    <xacro:property name="stick_radius" value="0.02"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_y" value="${stick_length / 2}"/>
    <xacro:property name="mass" value="1.0"/>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <!-- Stick structure -->
    <link name="stick">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${mass}" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                     iyy="0.001" iyz="0.0"
                     izz="0.001"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${stick_radius}" length="${stick_length}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${stick_radius}" length="${stick_length}"/>
            </geometry>
        </collision>
    </link>

    <!-- Left Wheel -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="stick"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                     iyy="0.001" iyz="0.0"
                     izz="0.001"/>
        </inertial>
    </link>

    <!-- Right Wheel -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="stick"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="0 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                     iyy="0.001" iyz="0.0"
                     izz="0.001"/>
        </inertial>
    </link>

</robot>
